# Generated by Django 3.2 on 2021-04-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facebook', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_google', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(blank=True, default='', null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_fb_user', models.BooleanField(default=False)),
                ('is_google_user', models.BooleanField(default=False)),
                ('last_active_date', models.DateTimeField(blank=True, null=True)),
                ('n_status', models.CharField(max_length=1)),
            ],
        ),
    ]
